### PR TITLE
Add BlockingToolbar

### PR DESCRIPTION
**Pull request by cbenhagen**
Use `BlockingToolbar` instead of `NSToolbar` to prevent maxmizing the window on double clicking a Flutter button. See https://github.com/macosui/macos_ui/issues/308

### CODE REVIEW

**Comment by Adrian-Samoticha** [comment]
Thanks. I will review this PR soon.

**Comment by Adrian-Samoticha** [comment]
I don’t fully understand the behavior of the blocking toolbar. It seems like it blocks double clicks from zooming the window when the right side of the window’s toolbar is double-clicked, while still triggering the zooming when the left side of the window is clicked. It doesn’t seem to check if a Flutter widget is blocking the toolbar from being clicked.

Unless I’m misunderstanding something, I don’t think this solves the linked issue. Ideally, there would be some way to check if a Flutter widget obstructs the toolbar at the clicked position, such that the clicks only get blocked when an actual widget is being clicked.

**Comment by cbenhagen** [comment]
Yes, ideally we would be able to check if a Flutter widget is in front of the toolbar and only block double clicks if this is the case. I haven't found a nice solution which allows to do this so I decided to block all double clicks to the toolbar. It is still better than zooming the window when the user double clicks a Flutter widget.

The issue you are describing is most likely due to the fact that you enable a native title in your window which will also handle the double clicks. I don't see a use case for enabling the native titles but if you do, you would most likely be better off using a completely native toolbar. 

To show what is happening I added a blue background to the `BlockingToolbar`
Screenshot 2023-11-28 at 11 53 21
Screenshot 2023-11-28 at 11 53 17

If you see a good use case to use the native titles with a Flutter toolbar then maybe a double click blocking variant of the title could be introduced?

**Comment by cbenhagen** [comment]
I also played with this idea but currently have dropped it. It might work but every Flutter widget you place in the toolbar would need to be made aware of this. Maybe we can leave this as an improvement for later?

**Comment by Adrian-Samoticha** [comment]
I think we could just offer a wrapper widget that you can wrap around your toolbar buttons, which would then handle the toolbar clicking automatically.

**Comment by cbenhagen** [comment]
Can this be merged without such a wrapper widget? I think this can be improved later if anyone needs it.

**Comment by Adrian-Samoticha** [comment]
I’d be willing to merge it if there was a method to enable and disable the blocking toolbar. Right now I think it’s too likely that some users may rely on the double-click-to-maximize feature in their apps to completely take it away with no way to enable it again.

Looking at your commit, I think all that’s necessary to achieve this is to add some sort of parameter of some sort to the `addToolbar` methods on both the Dart and the Swift side which controls whether the newly added toolbar is a `BlockingToolbar` or a plain `NSToolbar`.

If you’re unfamiliar with the way the platform channels are implemented in macos_window_utils, I’d be happy to do that myself.

**Comment by cbenhagen** [comment]
I'd happily accept that offer. Please feel free to push to this branch.

**Comment by Adrian-Samoticha** [comment]
How did you add the blue background to the `BlockingToolbar` in the screenshots you posted above? I would like to add a debug feature that allows the user to do that, but I cannot figure out how you did it.

**Comment by Adrian-Samoticha** [comment]
@cbenhagen Bump, in case you missed my previous comment.

**Comment by cbenhagen** [comment]
Sorry, I indeed missed your comment. Unfortunately I don't remember how I did it.

**Comment by Andre-lbc** [comment]
Hi,

I need something similar to this for my app, but my use case is quite complex (it is a tab bar, like in a browser; it has fixed buttons on the sides, it scrolls horizontally, tabs can have dynamic sizes, be pinned, grouped, moved, etc). My user should be able to "drag" items on the tab bar, but this currently also moves the window (I think I've already sorted this out by also overriding `mouseDownCanMoveWindow` of `NSView`).

I will create a custom plugin using method channels and try to link size and position of flutter widgets with an equivalent "passthrough" native toolbar item in order to avoid double click to maximize and click and hold to move the window behaviors. I might try to PR a backport of it into this project if I'm successful.

It would be nice if `MacosWindowUtilsConfig` had a boolean to avoid calling `await WindowManipulator.addToolbar();` in `apply()`, as my custom toolbar was being replaced with current implementation's empty toolbar (but I understand that this is very niched and already have a custom fix).

As a side note, in case you still need the background color @Adrian-Samoticha:

```dart
// ...
if itemIdentifier == NSToolbarItem.Identifier("BlockingItem") {
    let item = NSToolbarItem(itemIdentifier: itemIdentifier)
    let view = ForwardingView()
    view.flutterView = flutterView
    view.widthAnchor.constraint(lessThanOrEqualToConstant: 100000).isActive = true
    view.widthAnchor.constraint(greaterThanOrEqualToConstant: 1).isActive = true
    item.view = view
    // Add the following two lines
    view.wantsLayer = true
    view.layer?.backgroundColor = NSColor.green.cgColor
    return item
  }
  return nil
 // ...

```

**Comment by Andre-lbc** [comment]
I just received the merge notification and wanted to share my progress so far. 

Here are some previews (Please note that I'm using some custom widgets instead of `macos_ui`, so sizes may appear off—they are not final):

<details><summary>With debug overlay</summary>
<p>

https://github.com/user-attachments/assets/67de09be-3ee1-4d1a-85c8-8d4a145b1257

Overlay legend:
- Yellow: total usable toolbar area.
- Green: "Passthrough" UI (absorbs native events and send them to Flutter)

</p>
</details> 

<details><summary>Without debug overlays</summary>
<p>

https://github.com/user-attachments/assets/9058580d-dc5a-42dd-a173-1abdb9b62015

</p>
</details> 

The code is currently directly in my project. I'd like to discuss it before making a PR or migrating it to its own package.

Should I continue the conversation here, open a new issue, or start a discussion?

**Comment by Adrian-Samoticha** [comment]
@Andre-lbc Wow, that actually looks really good. I think moving this conversation into either a new issue or a discussion does make more sense than continuing it here.

Considering that the end goal is a PR, I suppose an issue makes the most sense.

**Comment by Andre-lbc** [comment]
For future readers: this proposal continues in https://github.com/macosui/macos_window_utils.dart/issues/53

**Pull request merged**
